### ISSUE TITLE
Support multiple currencies

### ISSUE THREAD

**Issue by l0b0** [inguin/moneybalance#12]
When expensing for example a holiday it can be very useful to have multiple input currencies and an arbitrary/multiple output currency/currencies. Conversion rates for specific dates can be fetched from official sources while online.

**Comment by inguin** [comment]
MoneyBalance 1.3 has been released and supports multiple currencies per calculation. Currencies and conversion rates must be configured manually ("Manage Currencies" in the drop-down menu). When exporting to CVS each expense has its own exchange rate column, so you can edit the sheet and use daily exchange rates before publishing your results.

F-Droid builds are already available.

**Comment by inguin** [comment]
BTW, Warning: After installing 1.3, DO NOT downgrade back to an older version or you will lose all your data.
