### ISSUE TITLE
Add more  than10 persons

### ISSUE THREAD

**Issue by monsieurmartin** [inguin/moneybalance#13]
Hi,

I have used this brilliant app for months and months and only recently, I needed to split money for more than 10 persons. I was surprised to notice that there was a limit. I mean, we are not often dealing with 99 persons, but a reasonable 15+ can happen.

I assume my query is not that complicated -I may be wrong though. What could it be done about this?

Thanks much.

M.

**Comment by inguin** [comment]
You're right, the 10 person limit is completely arbitrary. I increased the limit to 100 now.

It's been way to long since I did any work on this project. I'll see if I can contact the guys who contributed the French and Spanish translations, then I'll release a new version.

**Comment by monsieurmartin** [comment]
Okay cheers. I can give some help for the French and Spanish translation (native languages).

**Comment by inguin** [comment]
Sounds perfect. Pop over to #14 to see what strings need updating. If you're familiar with git you can clone my project, update the files (res/values-es and res/values-fr) and create a pull request. If not, just add a comment with your recommended translations. Still, it might be helpful to look at the existing translations for reference.

**Comment by inguin** [comment]
Thanks for the translations! Version 1.3 has been released, new package is available from f-droid. Note: Do not downgrade from 1.3 to 1.2 or you will lose all your data!
