### ISSUE TITLE
Update French and Spanish translations for release

### ISSUE THREAD

**Issue by inguin** [inguin/moneybalance#14]
@Djiko @perdigano: After years of lazy idleness I have finally found the motivation to prepare a new release of my moneybalance app. The biggest new feature is the support of multiple currencies in a single calculation, which also required adding some new strings.

Could you please provide updated translations for the following strings:

- calculation_currency (changed from "Currency" to "Main Currency")
- manage_currencies
- additional_currencies
- add_currency

@perdigano: I'm awfully sorry for the long wait! I'll get a new release out ASAP.

**Comment by inguin** [comment]
Closed by pull requests #16 and #17.

**Comment by Djiko** [comment]
@inguin 
I'll take care of a complete review. Some strings are hardcoded in the AboutDialog activity though. Is this wanted?

**Comment by inguin** [comment]
@Djiko
Great, thanks! The AboutDialog is certainly a candidate for translation, I just never got around to implement it. Also, more importantly, it should display the application version number and build date.

**Comment by Djiko** [comment]
@inguin 
Done in pull request #19
