### ISSUE TITLE
Balance not available

### ISSUE THREAD

**Issue by jschaeff** [inguin/moneybalance#18]
[Uploading test.txt…]()

Hi,

thank you for this app, The opensource alternative was missing.
The app is failing when I try to show a "résumé" of some simple expenses. I exported a CSV of the expenses that shows the problem. Any idea ? Maybe the locale of the numbers are not supported. The coma is used as a decimal separator.

**Comment by inguin** [comment]
Darn, I broke that while cleaning up some code for 1.3. I have no idea why I didn't notice it before releasing. I'm very sorry!

I just released a bugfix version 1.3.1, but it may take a day or two before f-droid will pick it up. Please do not downgrade to 1.2, or you will lose your data!

**Comment by jschaeff** [comment]
The update works fine. Thank you
